Fix iapyx urls (#193)
* Fixing iapyx bug in url paths, which is causing that user cannot send a proper vote. This PR is adding `api` to vitss client while removing it from proxy and node

* downgrade click (pip install click==8.0.4) to avoid issue in typer:
ImportError: cannot import name 'get_terminal_size' from 'click.termui'